import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { toast } from 'sonner';
import { cn } from '../utils/cn';
import { formatDateTime } from '../utils/date';
import {
  Plus,
  Search,
  Filter,
  Trash2,
  Loader2,
  ChevronLeft,
  ChevronRight,
  Download,
  FileText,
  BarChart2,
} from 'lucide-react';
import { Report, PaginatedResponse } from '../../../../packages/shared/src';
import ReportModal from '../components/ReportModal';
import ConfirmDialog from '../components/ConfirmDialog';

const typeColors = {
  production: 'bg-blue-500/10 text-blue-400',
  worker: 'bg-green-500/10 text-green-400',
  machine: 'bg-purple-500/10 text-purple-400',
  shift: 'bg-orange-500/10 text-orange-400',
  quality: 'bg-red-500/10 text-red-400',
};

export default function Reports() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [total, setTotal] = useState(0);
  const [typeFilter, setTypeFilter] = useState('');
  const [modalOpen, setModalOpen] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<Report | null>(null);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams({
        page: page.toString(),
        page_size: pageSize.toString(),
      });
      if (typeFilter) params.set('type', typeFilter);

      const res = await api.get<PaginatedResponse<Report>>(`/api/reports?${params}`);
      setReports(res.data);
      setTotal(res.total);
    } catch (error) {
      toast.error('Failed to load reports');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, [page, pageSize, typeFilter]);

  const handleDownload = async (report: Report) => {
    if (report.file_url) {
      window.open(report.file_url, '_blank');
    } else {
      toast.error('Report file not available');
    }
  };

  const handleDelete = async (report: Report) => {
    try {
      await api.delete(`/api/reports/${report.id}`);
      toast.success('Report deleted');
      fetchReports();
    } catch (error) {
      toast.error('Failed to delete report');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Reports</h1>
          <p className="text-slate-400">Generate and manage reports</p>
        </div>
        <button
          onClick={() => setModalOpen(true)}
          className="flex items-center gap-2 px-4 py-2 bg-brand-600 hover:bg-brand-700 text-white rounded-lg font-medium transition-colors"
        >
          <Plus className="h-4 w-4" />
          Generate Report
        </button>
      </div>

      <div className="bg-slate-800 rounded-xl border border-slate-700 p-4">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
            <input type="text" placeholder="Search reports..." className="w-full pl-10 pr-4 py-2 rounded-lg bg-slate-900 border border-slate-600 text-white placeholder-slate-500" />
          </div>
          <select value={typeFilter} onChange={e => { setTypeFilter(e.target.value); setPage(1); }} className="px-4 py-2 rounded-lg bg-slate-900 border border-slate-600 text-white">
            <option value="">All Types</option>
            <option value="production">Production</option>
            <option value="worker">Worker</option>
            <option value="machine">Machine</option>
            <option value="shift">Shift</option>
            <option value="quality">Quality</option>
          </select>
        </div>
      </div>

      <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden">
        {loading ? (
          <div className="p-8 text-center"><Loader2 className="h-8 w-8 animate-spin text-brand-500 mx-auto" /></div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full" role="table">
                <thead className="bg-slate-900/50">
                  <tr>
                    {[
                      { key: 'name', label: 'Name' },
                      { key: 'type', label: 'Type' },
                      { key: 'generated_by_name', label: 'Generated By' },
                      { key: 'generated_at', label: 'Generated At' },
                      { key: 'file_url', label: 'File' },
                      { key: 'actions', label: '' },
                    ].map(col => (
                      <th key={col.key} scope="col" className="px-4 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">{col.label}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-700">
                  {reports.map(report => (
                    <tr key={report.id} className="hover:bg-slate-700/50 transition-colors">
                      <td className="px-4 py-3 font-medium text-white">{report.name}</td>
                      <td className="px-4 py-3">
                        <span className={cn('inline-flex px-2 py-1 rounded-full text-xs font-medium capitalize', typeColors[report.type as keyof typeof typeColors])}>
                          {report.type}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-sm text-slate-300">{report.generated_by_name || 'Unknown'}</td>
                      <td className="px-4 py-3 text-sm text-slate-300">{formatDateTime(report.generated_at)}</td>
                      <td className="px-4 py-3">
                        {report.file_url ? (
                          <span className="inline-flex items-center gap-1 text-green-400 text-sm"><FileText className="h-3 w-3" /> Available</span>
                        ) : (
                          <span className="text-slate-500 text-sm">Pending</span>
                        )}
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center justify-end gap-1">
                          {report.file_url && (
                            <button onClick={() => handleDownload(report)} className="p-1.5 rounded-lg text-slate-400 hover:bg-slate-700 hover:text-white"><Download className="h-4 w-4" /></button>
                          )}
                          <button onClick={() => setDeleteConfirm(report)} className="p-1.5 rounded-lg text-slate-400 hover:bg-slate-700 hover:text-red-400"><Trash2 className="h-4 w-4" /></button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {total > pageSize && (
              <div className="px-4 py-3 border-t border-slate-700 flex items-center justify-between">
                <p className="text-sm text-slate-400">Showing {((page - 1) * pageSize) + 1} to {Math.min(page * pageSize, total)} of {total}</p>
                <div className="flex items-center gap-2">
                  <button onClick={() => setPage(p => p - 1)} disabled={page === 1} className="p-2 rounded-lg bg-slate-900 border border-slate-600 text-slate-300 hover:bg-slate-700 disabled:opacity-50"><ChevronLeft className="h-4 w-4" /></button>
                  <button onClick={() => setPage(p => p + 1)} disabled={page * pageSize >= total} className="p-2 rounded-lg bg-slate-900 border border-slate-600 text-slate-300 hover:bg-slate-700 disabled:opacity-50"><ChevronRight className="h-4 w-4" /></button>
                </div>
              </div>
            )}
          </>
        )}
      </div>

      <ReportModal isOpen={modalOpen} onClose={() => setModalOpen(false)} onSuccess={fetchReports} />
      <ConfirmDialog isOpen={!!deleteConfirm} onClose={() => setDeleteConfirm(null)} onConfirm={() => { handleDelete(deleteConfirm!); setDeleteConfirm(null); }} title="Delete Report" message="Delete this report?" variant="destructive" />
    </div>
  );
}


